name: maenbal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flick_video_player: ^0.8.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  google_fonts: ^6.2.0
  image_picker: ^1.1.2
  nb_utils: ^7.0.3
  provider: ^6.1.2
  url_launcher: ^6.3.0
  video_player: ^2.8.7
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/videos/
